### ISSUE TITLE
agrega perro a mi poema

### ISSUE THREAD

**Issue by Jared-gtz** [Jared-gtz/POEMA-TAREA-3-#1]
el perro es de color azul y muy grande y muy bravo.  Además el perro es muy jugueton y lindo llamado firulais 
![perro](https://user-images.githubusercontent.com/42589815/44500153-d1a86700-a64c-11e8-820d-130ab29212e9.png)
el perro estará despierto?

**Comment by Jared-gtz** [comment]
describir si es o no el perro asi

**Comment by RogelioLetechipia** [comment]
Agrego el commit hash para hacer referencia a la modificacion.
 861b4fe
